CREATE TABLE IF NOT EXISTS "__EFMigrationsHistory" (
    "MigrationId" character varying(150) NOT NULL,
    "ProductVersion" character varying(32) NOT NULL,
    CONSTRAINT "PK___EFMigrationsHistory" PRIMARY KEY ("MigrationId")
);

START TRANSACTION;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260806132931_InitialCreate') THEN
        IF NOT EXISTS(SELECT 1 FROM pg_namespace WHERE nspname = 'wesal') THEN
            CREATE SCHEMA wesal;
        END IF;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260806132931_InitialCreate') THEN
    CREATE TABLE wesal."AspNetRoles" (
        "Id" text NOT NULL,
        "Name" character varying(256),
        "NormalizedName" character varying(256),
        "ConcurrencyStamp" text,
        CONSTRAINT "PK_AspNetRoles" PRIMARY KEY ("Id")
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260806132931_InitialCreate') THEN
    CREATE TABLE wesal."AspNetUsers" (
        "Id" text NOT NULL,
        "FullName" character varying(150) NOT NULL,
        "PreferredLanguage" integer NOT NULL,
        "UserName" character varying(256),
        "NormalizedUserName" character varying(256),
        "Email" character varying(256),
        "NormalizedEmail" character varying(256),
        "EmailConfirmed" boolean NOT NULL,
        "PasswordHash" text,
        "SecurityStamp" text,
        "ConcurrencyStamp" text,
        "PhoneNumber" text,
        "PhoneNumberConfirmed" boolean NOT NULL,
        "TwoFactorEnabled" boolean NOT NULL,
        "LockoutEnd" timestamp with time zone,
        "LockoutEnabled" boolean NOT NULL,
        "AccessFailedCount" integer NOT NULL,
        CONSTRAINT "PK_AspNetUsers" PRIMARY KEY ("Id")
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260806132931_InitialCreate') THEN
    CREATE TABLE wesal."Halls" (
        "Id" uuid NOT NULL,
        "Name" character varying(200) NOT NULL,
        "MainImageUrl" character varying(500),
        "ContactPhone" character varying(30),
        "Region" integer NOT NULL,
        "Address" character varying(500) NOT NULL,
        "Capacity" integer NOT NULL,
        "Price" numeric(12,2),
        "ShowPrice" boolean NOT NULL,
        "Description" character varying(2000),
        "Status" integer NOT NULL,
        "IsDeleted" boolean NOT NULL,
        "OwnerId" text,
        "CreatedAt" timestamp with time zone NOT NULL,
        "CreatedBy" text,
        "UpdatedAt" timestamp with time zone,
        "UpdatedBy" text,
        CONSTRAINT "PK_Halls" PRIMARY KEY ("Id")
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260806132931_InitialCreate') THEN
    CREATE TABLE wesal."AspNetRoleClaims" (
        "Id" integer GENERATED BY DEFAULT AS IDENTITY,
        "RoleId" text NOT NULL,
        "ClaimType" text,
        "ClaimValue" text,
        CONSTRAINT "PK_AspNetRoleClaims" PRIMARY KEY ("Id"),
        CONSTRAINT "FK_AspNetRoleClaims_AspNetRoles_RoleId" FOREIGN KEY ("RoleId") REFERENCES wesal."AspNetRoles" ("Id") ON DELETE CASCADE
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260806132931_InitialCreate') THEN
    CREATE TABLE wesal."AspNetUserClaims" (
        "Id" integer GENERATED BY DEFAULT AS IDENTITY,
        "UserId" text NOT NULL,
        "ClaimType" text,
        "ClaimValue" text,
        CONSTRAINT "PK_AspNetUserClaims" PRIMARY KEY ("Id"),
        CONSTRAINT "FK_AspNetUserClaims_AspNetUsers_UserId" FOREIGN KEY ("UserId") REFERENCES wesal."AspNetUsers" ("Id") ON DELETE CASCADE
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260806132931_InitialCreate') THEN
    CREATE TABLE wesal."AspNetUserLogins" (
        "LoginProvider" text NOT NULL,
        "ProviderKey" text NOT NULL,
        "ProviderDisplayName" text,
        "UserId" text NOT NULL,
        CONSTRAINT "PK_AspNetUserLogins" PRIMARY KEY ("LoginProvider", "ProviderKey"),
        CONSTRAINT "FK_AspNetUserLogins_AspNetUsers_UserId" FOREIGN KEY ("UserId") REFERENCES wesal."AspNetUsers" ("Id") ON DELETE CASCADE
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260806132931_InitialCreate') THEN
    CREATE TABLE wesal."AspNetUserRoles" (
        "UserId" text NOT NULL,
        "RoleId" text NOT NULL,
        CONSTRAINT "PK_AspNetUserRoles" PRIMARY KEY ("UserId", "RoleId"),
        CONSTRAINT "FK_AspNetUserRoles_AspNetRoles_RoleId" FOREIGN KEY ("RoleId") REFERENCES wesal."AspNetRoles" ("Id") ON DELETE CASCADE,
        CONSTRAINT "FK_AspNetUserRoles_AspNetUsers_UserId" FOREIGN KEY ("UserId") REFERENCES wesal."AspNetUsers" ("Id") ON DELETE CASCADE
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260806132931_InitialCreate') THEN
    CREATE TABLE wesal."AspNetUserTokens" (
        "UserId" text NOT NULL,
        "LoginProvider" text NOT NULL,
        "Name" text NOT NULL,
        "Value" text,
        CONSTRAINT "PK_AspNetUserTokens" PRIMARY KEY ("UserId", "LoginProvider", "Name"),
        CONSTRAINT "FK_AspNetUserTokens_AspNetUsers_UserId" FOREIGN KEY ("UserId") REFERENCES wesal."AspNetUsers" ("Id") ON DELETE CASCADE
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260806132931_InitialCreate') THEN
    CREATE TABLE wesal."HallAvailabilities" (
        "Id" uuid NOT NULL,
        "HallId" uuid NOT NULL,
        "Date" date NOT NULL,
        "PeriodType" integer NOT NULL,
        "Status" integer NOT NULL,
        "CreatedAt" timestamp with time zone NOT NULL,
        "CreatedBy" text,
        "UpdatedAt" timestamp with time zone,
        "UpdatedBy" text,
        CONSTRAINT "PK_HallAvailabilities" PRIMARY KEY ("Id"),
        CONSTRAINT "FK_HallAvailabilities_Halls_HallId" FOREIGN KEY ("HallId") REFERENCES wesal."Halls" ("Id") ON DELETE CASCADE
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260806132931_InitialCreate') THEN
    CREATE TABLE wesal."HallBookingPeriods" (
        "Id" uuid NOT NULL,
        "HallId" uuid NOT NULL,
        "Type" integer NOT NULL,
        "StartTime" time NOT NULL,
        "EndTime" time NOT NULL,
        CONSTRAINT "PK_HallBookingPeriods" PRIMARY KEY ("Id"),
        CONSTRAINT "FK_HallBookingPeriods_Halls_HallId" FOREIGN KEY ("HallId") REFERENCES wesal."Halls" ("Id") ON DELETE CASCADE
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260806132931_InitialCreate') THEN
    CREATE INDEX "IX_AspNetRoleClaims_RoleId" ON wesal."AspNetRoleClaims" ("RoleId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260806132931_InitialCreate') THEN
    CREATE UNIQUE INDEX "RoleNameIndex" ON wesal."AspNetRoles" ("NormalizedName");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260806132931_InitialCreate') THEN
    CREATE INDEX "IX_AspNetUserClaims_UserId" ON wesal."AspNetUserClaims" ("UserId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260806132931_InitialCreate') THEN
    CREATE INDEX "IX_AspNetUserLogins_UserId" ON wesal."AspNetUserLogins" ("UserId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260806132931_InitialCreate') THEN
    CREATE INDEX "IX_AspNetUserRoles_RoleId" ON wesal."AspNetUserRoles" ("RoleId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260806132931_InitialCreate') THEN
    CREATE INDEX "EmailIndex" ON wesal."AspNetUsers" ("NormalizedEmail");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260806132931_InitialCreate') THEN
    CREATE UNIQUE INDEX "UserNameIndex" ON wesal."AspNetUsers" ("NormalizedUserName");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260806132931_InitialCreate') THEN
    CREATE UNIQUE INDEX "IX_HallAvailabilities_HallId_Date_PeriodType" ON wesal."HallAvailabilities" ("HallId", "Date", "PeriodType");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260806132931_InitialCreate') THEN
    CREATE UNIQUE INDEX "IX_HallBookingPeriods_HallId_Type" ON wesal."HallBookingPeriods" ("HallId", "Type");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260806132931_InitialCreate') THEN
    CREATE INDEX "IX_Halls_Region" ON wesal."Halls" ("Region");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260806132931_InitialCreate') THEN
    CREATE INDEX "IX_Halls_Status" ON wesal."Halls" ("Status");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260806132931_InitialCreate') THEN
    CREATE INDEX "IX_Halls_Status_IsDeleted" ON wesal."Halls" ("Status", "IsDeleted");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260806132931_InitialCreate') THEN
    INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
    VALUES ('20260806132931_InitialCreate', '10.0.10');
    END IF;
END $EF$;
COMMIT;

START TRANSACTION;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260815163300_AddHallImages') THEN
    CREATE TABLE wesal."HallImages" (
        "Id" uuid NOT NULL,
        "HallId" uuid NOT NULL,
        "Url" character varying(500) NOT NULL,
        "DisplayOrder" integer NOT NULL,
        "IsDeleted" boolean NOT NULL,
        "CreatedAt" timestamp with time zone NOT NULL,
        "CreatedBy" text,
        "UpdatedAt" timestamp with time zone,
        "UpdatedBy" text,
        CONSTRAINT "PK_HallImages" PRIMARY KEY ("Id"),
        CONSTRAINT "FK_HallImages_Halls_HallId" FOREIGN KEY ("HallId") REFERENCES wesal."Halls" ("Id") ON DELETE CASCADE
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260815163300_AddHallImages') THEN
    CREATE INDEX "IX_HallImages_HallId_DisplayOrder" ON wesal."HallImages" ("HallId", "DisplayOrder");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260815163300_AddHallImages') THEN
    CREATE INDEX "IX_HallImages_HallId_IsDeleted" ON wesal."HallImages" ("HallId", "IsDeleted");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260815163300_AddHallImages') THEN
    INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
    VALUES ('20260815163300_AddHallImages', '10.0.10');
    END IF;
END $EF$;
COMMIT;

START TRANSACTION;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260818090636_AddRatingsWithComments') THEN
    CREATE TABLE wesal."Comments" (
        "Id" uuid NOT NULL,
        "HallId" uuid NOT NULL,
        "UserId" character varying(450) NOT NULL,
        "Content" character varying(1000) NOT NULL,
        "CreatedAt" timestamp with time zone NOT NULL,
        "CreatedBy" text,
        "UpdatedAt" timestamp with time zone,
        "UpdatedBy" text,
        CONSTRAINT "PK_Comments" PRIMARY KEY ("Id"),
        CONSTRAINT "FK_Comments_Halls_HallId" FOREIGN KEY ("HallId") REFERENCES wesal."Halls" ("Id") ON DELETE CASCADE
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260818090636_AddRatingsWithComments') THEN
    CREATE TABLE wesal."Ratings" (
        "Id" uuid NOT NULL,
        "HallId" uuid NOT NULL,
        "UserId" character varying(450) NOT NULL,
        "Value" integer NOT NULL,
        "CreatedAt" timestamp with time zone NOT NULL,
        "CreatedBy" text,
        "UpdatedAt" timestamp with time zone,
        "UpdatedBy" text,
        CONSTRAINT "PK_Ratings" PRIMARY KEY ("Id"),
        CONSTRAINT "CK_Ratings_Value" CHECK ("Value" BETWEEN 1 AND 5),
        CONSTRAINT "FK_Ratings_AspNetUsers_UserId" FOREIGN KEY ("UserId") REFERENCES wesal."AspNetUsers" ("Id") ON DELETE CASCADE,
        CONSTRAINT "FK_Ratings_Halls_HallId" FOREIGN KEY ("HallId") REFERENCES wesal."Halls" ("Id") ON DELETE CASCADE
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260818090636_AddRatingsWithComments') THEN
    CREATE INDEX "IX_Comments_HallId" ON wesal."Comments" ("HallId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260818090636_AddRatingsWithComments') THEN
    CREATE UNIQUE INDEX "IX_Ratings_HallId_UserId" ON wesal."Ratings" ("HallId", "UserId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260818090636_AddRatingsWithComments') THEN
    CREATE INDEX "IX_Ratings_UserId" ON wesal."Ratings" ("UserId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260818090636_AddRatingsWithComments') THEN
    INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
    VALUES ('20260818090636_AddRatingsWithComments', '10.0.10');
    END IF;
END $EF$;
COMMIT;

START TRANSACTION;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260818092613_AddCommentsDataValidation') THEN
    DROP INDEX wesal."IX_Comments_HallId";
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260818092613_AddCommentsDataValidation') THEN
    CREATE INDEX "IX_Comments_HallId_CreatedAt" ON wesal."Comments" ("HallId", "CreatedAt");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260818092613_AddCommentsDataValidation') THEN
    CREATE INDEX "IX_Comments_UserId" ON wesal."Comments" ("UserId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260818092613_AddCommentsDataValidation') THEN
    ALTER TABLE wesal."Comments" ADD CONSTRAINT "FK_Comments_AspNetUsers_UserId" FOREIGN KEY ("UserId") REFERENCES wesal."AspNetUsers" ("Id") ON DELETE CASCADE;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260818092613_AddCommentsDataValidation') THEN
    INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
    VALUES ('20260818092613_AddCommentsDataValidation', '10.0.10');
    END IF;
END $EF$;
COMMIT;

START TRANSACTION;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260825101619_AISessionStorage') THEN
    CREATE TABLE wesal."AISessions" (
        "Id" uuid NOT NULL,
        "SessionId" character varying(450),
        "IsGuestSession" boolean NOT NULL,
        "UserId" character varying(450),
        "CreatedAt" timestamp with time zone NOT NULL,
        "LastAccessedAt" timestamp with time zone,
        "Status" character varying(500),
        "AiServiceStatus" character varying(500),
        "GuestIdentifier" character varying(450),
        CONSTRAINT "PK_AISessions" PRIMARY KEY ("Id")
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260825101619_AISessionStorage') THEN
    CREATE TABLE wesal."Conversations" (
        "Id" uuid NOT NULL,
        "HallId" uuid NOT NULL,
        "SenderUserId" character varying(450) NOT NULL,
        "HallOwnerId" character varying(450) NOT NULL,
        "CreatedAt" timestamp with time zone NOT NULL,
        "CreatedBy" text,
        "UpdatedAt" timestamp with time zone,
        "UpdatedBy" text,
        CONSTRAINT "PK_Conversations" PRIMARY KEY ("Id"),
        CONSTRAINT "FK_Conversations_Halls_HallId" FOREIGN KEY ("HallId") REFERENCES wesal."Halls" ("Id") ON DELETE CASCADE
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260825101619_AISessionStorage') THEN
    CREATE UNIQUE INDEX "IX_AISessions_SessionId" ON wesal."AISessions" ("SessionId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260825101619_AISessionStorage') THEN
    CREATE INDEX "IX_AISessions_IsGuestSession_GuestIdentifier" ON wesal."AISessions" ("IsGuestSession", "GuestIdentifier");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260825101619_AISessionStorage') THEN
    CREATE INDEX "IX_AISessions_UserId_IsGuestSession" ON wesal."AISessions" ("UserId", "IsGuestSession");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260825101619_AISessionStorage') THEN
    CREATE INDEX "IX_Conversations_HallId" ON wesal."Conversations" ("HallId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260825101619_AISessionStorage') THEN
    INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
    VALUES ('20260825101619_AISessionStorage', '10.0.10');
    END IF;
END $EF$;
COMMIT;

START TRANSACTION;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260829111638_RevokedTokens') THEN
    CREATE TABLE wesal."RevokedTokens" (
        "Id" uuid NOT NULL,
        "Jti" character varying(450) NOT NULL,
        "UserId" character varying(450) NOT NULL,
        "RevokedAt" timestamp with time zone NOT NULL,
        CONSTRAINT "PK_RevokedTokens" PRIMARY KEY ("Id")
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260829111638_RevokedTokens') THEN
    CREATE UNIQUE INDEX "IX_RevokedTokens_Jti" ON wesal."RevokedTokens" ("Jti");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260829111638_RevokedTokens') THEN
    INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
    VALUES ('20260829111638_RevokedTokens', '10.0.10');
    END IF;
END $EF$;
COMMIT;

START TRANSACTION;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260829120033_AddMessages') THEN
    CREATE TABLE wesal."Messages" (
        "Id" uuid NOT NULL,
        "ConversationId" uuid NOT NULL,
        "SenderUserId" character varying(450) NOT NULL,
        "Content" character varying(1000) NOT NULL,
        "CreatedAt" timestamp with time zone NOT NULL,
        "CreatedBy" text,
        "UpdatedAt" timestamp with time zone,
        "UpdatedBy" text,
        CONSTRAINT "PK_Messages" PRIMARY KEY ("Id"),
        CONSTRAINT "FK_Messages_Conversations_ConversationId" FOREIGN KEY ("ConversationId") REFERENCES wesal."Conversations" ("Id") ON DELETE CASCADE
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260829120033_AddMessages') THEN
    CREATE INDEX "IX_Messages_ConversationId_CreatedAt" ON wesal."Messages" ("ConversationId", "CreatedAt");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260829120033_AddMessages') THEN
    INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
    VALUES ('20260829120033_AddMessages', '10.0.10');
    END IF;
END $EF$;
COMMIT;

START TRANSACTION;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260829123028_AddBookings') THEN
    CREATE TABLE wesal."Bookings" (
        "Id" uuid NOT NULL,
        "HallId" uuid NOT NULL,
        "RequesterUserId" character varying(450) NOT NULL,
        "Date" date NOT NULL,
        "Period" integer NOT NULL,
        "Status" integer NOT NULL,
        "RejectionReason" character varying(1000),
        "RejectionMessageId" uuid,
        "CreatedAt" timestamp with time zone NOT NULL,
        "CreatedBy" text,
        "UpdatedAt" timestamp with time zone,
        "UpdatedBy" text,
        CONSTRAINT "PK_Bookings" PRIMARY KEY ("Id"),
        CONSTRAINT "FK_Bookings_Halls_HallId" FOREIGN KEY ("HallId") REFERENCES wesal."Halls" ("Id") ON DELETE CASCADE
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260829123028_AddBookings') THEN
    CREATE INDEX "IX_Bookings_HallId_RequesterUserId" ON wesal."Bookings" ("HallId", "RequesterUserId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260829123028_AddBookings') THEN
    CREATE UNIQUE INDEX "IX_Bookings_RejectionMessageId" ON wesal."Bookings" ("RejectionMessageId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260829123028_AddBookings') THEN
    INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
    VALUES ('20260829123028_AddBookings', '10.0.10');
    END IF;
END $EF$;
COMMIT;

START TRANSACTION;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260901082714_AddUniquePhoneNumberIndex') THEN
    CREATE UNIQUE INDEX "IX_AspNetUsers_PhoneNumber" ON wesal."AspNetUsers" ("PhoneNumber") WHERE "PhoneNumber" IS NOT NULL;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260901082714_AddUniquePhoneNumberIndex') THEN
    INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
    VALUES ('20260901082714_AddUniquePhoneNumberIndex', '10.0.10');
    END IF;
END $EF$;
COMMIT;

START TRANSACTION;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260901160342_AddMessageClientRequestId') THEN
    ALTER TABLE wesal."Messages" ADD "ClientRequestId" character varying(450);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260901160342_AddMessageClientRequestId') THEN
    CREATE UNIQUE INDEX "IX_Messages_SenderUserId_ClientRequestId" ON wesal."Messages" ("SenderUserId", "ClientRequestId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260901160342_AddMessageClientRequestId') THEN
    INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
    VALUES ('20260901160342_AddMessageClientRequestId', '10.0.10');
    END IF;
END $EF$;
COMMIT;

START TRANSACTION;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260902080929_AddBookingPeriodIndex') THEN
    CREATE INDEX "IX_Bookings_HallId_Date_Period_Status" ON wesal."Bookings" ("HallId", "Date", "Period", "Status");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260902080929_AddBookingPeriodIndex') THEN
    INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
    VALUES ('20260902080929_AddBookingPeriodIndex', '10.0.10');
    END IF;
END $EF$;
COMMIT;

START TRANSACTION;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260912090602_AddBookingPublicationState') THEN
    ALTER TABLE wesal."Bookings" ADD "IsPublished" boolean NOT NULL DEFAULT FALSE;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260912090602_AddBookingPublicationState') THEN
    INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
    VALUES ('20260912090602_AddBookingPublicationState', '10.0.10');
    END IF;
END $EF$;
COMMIT;

START TRANSACTION;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260912133110_AddHallSubscriptionState') THEN
    ALTER TABLE wesal."Halls" ADD "IsAdminLocked" boolean NOT NULL DEFAULT FALSE;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260912133110_AddHallSubscriptionState') THEN
    ALTER TABLE wesal."Halls" ADD "SubscriptionCycleEnd" date;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260912133110_AddHallSubscriptionState') THEN
    INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
    VALUES ('20260912133110_AddHallSubscriptionState', '10.0.10');
    END IF;
END $EF$;
COMMIT;

START TRANSACTION;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260914114000_AddHallPaymentAndLockExecutionState') THEN
    ALTER TABLE wesal."Halls" ADD "LockedAt" timestamp with time zone;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260914114000_AddHallPaymentAndLockExecutionState') THEN
    ALTER TABLE wesal."Halls" ADD "LockedByAdminUserId" text;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260914114000_AddHallPaymentAndLockExecutionState') THEN
    ALTER TABLE wesal."Halls" ADD "PaymentStatus" integer NOT NULL DEFAULT 0;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260914114000_AddHallPaymentAndLockExecutionState') THEN
    ALTER TABLE wesal."Halls" ADD "SubscriptionCycleStart" date;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260914114000_AddHallPaymentAndLockExecutionState') THEN
    ALTER TABLE wesal."Halls" ADD "SystemLocked" boolean NOT NULL DEFAULT FALSE;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260914114000_AddHallPaymentAndLockExecutionState') THEN
    CREATE INDEX "IX_Halls_Status_PaymentStatus_SystemLocked_SubscriptionCycleEnd" ON wesal."Halls" ("Status", "PaymentStatus", "SystemLocked", "SubscriptionCycleEnd");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260914114000_AddHallPaymentAndLockExecutionState') THEN
    UPDATE "wesal"."Halls" SET "PaymentStatus" = 1 WHERE "Status" = 1;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260914114000_AddHallPaymentAndLockExecutionState') THEN
    INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
    VALUES ('20260914114000_AddHallPaymentAndLockExecutionState', '10.0.10');
    END IF;
END $EF$;
COMMIT;

START TRANSACTION;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260914195607_AddAdminUnlockAndWarningTracking') THEN
    ALTER TABLE wesal."Halls" ADD "UnlockedAt" timestamp with time zone;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260914195607_AddAdminUnlockAndWarningTracking') THEN
    ALTER TABLE wesal."Halls" ADD "UnlockedByAdminUserId" text;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260914195607_AddAdminUnlockAndWarningTracking') THEN
    ALTER TABLE wesal."Halls" ADD "WarningSentAttempts" integer NOT NULL DEFAULT 0;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260914195607_AddAdminUnlockAndWarningTracking') THEN
    ALTER TABLE wesal."Halls" ADD "WarningSentForCycleEnd" date;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260914195607_AddAdminUnlockAndWarningTracking') THEN
    INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
    VALUES ('20260914195607_AddAdminUnlockAndWarningTracking', '10.0.10');
    END IF;
END $EF$;
COMMIT;

START TRANSACTION;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260920145207_AddHallDetailedContentAndDocuments') THEN
    ALTER TABLE wesal."Halls" ADD "DetailedAddress" character varying(150);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260920145207_AddHallDetailedContentAndDocuments') THEN
    ALTER TABLE wesal."Halls" ADD "OtherFeatures" character varying(200);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260920145207_AddHallDetailedContentAndDocuments') THEN
    ALTER TABLE wesal."Halls" ADD "PaymentReceiptUploadedAt" timestamp with time zone;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260920145207_AddHallDetailedContentAndDocuments') THEN
    ALTER TABLE wesal."Halls" ADD "PaymentReceiptUrl" character varying(500);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260920145207_AddHallDetailedContentAndDocuments') THEN
    ALTER TABLE wesal."Halls" ADD "YouTubeVideoUrl" character varying(500);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260920145207_AddHallDetailedContentAndDocuments') THEN
    ALTER TABLE wesal."AspNetUsers" ADD "IdentityDocumentUploadedAt" timestamp with time zone;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260920145207_AddHallDetailedContentAndDocuments') THEN
    ALTER TABLE wesal."AspNetUsers" ADD "IdentityDocumentUrl" character varying(500);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260920145207_AddHallDetailedContentAndDocuments') THEN
    CREATE TABLE wesal."HallFeatures" (
        "Id" uuid NOT NULL,
        "HallId" uuid NOT NULL,
        "Name" character varying(100) NOT NULL,
        CONSTRAINT "PK_HallFeatures" PRIMARY KEY ("Id"),
        CONSTRAINT "FK_HallFeatures_Halls_HallId" FOREIGN KEY ("HallId") REFERENCES wesal."Halls" ("Id") ON DELETE CASCADE
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260920145207_AddHallDetailedContentAndDocuments') THEN
    CREATE UNIQUE INDEX "IX_HallFeatures_HallId_Name" ON wesal."HallFeatures" ("HallId", "Name");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260920145207_AddHallDetailedContentAndDocuments') THEN
    INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
    VALUES ('20260920145207_AddHallDetailedContentAndDocuments', '10.0.10');
    END IF;
END $EF$;
COMMIT;

START TRANSACTION;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260921123939_AddConversationReadState') THEN
    CREATE TABLE wesal."ConversationReadStates" (
        "ConversationId" uuid NOT NULL,
        "UserId" character varying(450) NOT NULL,
        "LastReadAt" timestamp with time zone NOT NULL,
        CONSTRAINT "PK_ConversationReadStates" PRIMARY KEY ("ConversationId", "UserId"),
        CONSTRAINT "FK_ConversationReadStates_Conversations_ConversationId" FOREIGN KEY ("ConversationId") REFERENCES wesal."Conversations" ("Id") ON DELETE CASCADE
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260921123939_AddConversationReadState') THEN
    INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
    VALUES ('20260921123939_AddConversationReadState', '10.0.10');
    END IF;
END $EF$;
COMMIT;

